// ../art/**.json  ->  src/art/pieces.json
//
// READ-ONLY over ../art. Writes only inside dapp/.
//
// The collection's art is 71 drawings of 32x32 palette indices — 70 traits and
// one locked base — plus a 48-slot palette. Packed one byte per pixel and
// base64'd, the whole set is about 97 KB, which the site loads once and then
// composes any of the 1,866,240 combinations from without a chain, a server or
// an image request.
//
//   node scripts/build-art.mjs

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadPieces } from '../../tools/pieces.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '..', 'src', 'art', 'pieces.json');
const LORE = path.join(HERE, '..', '..', 'lore', 'traits.md');

const L = loadPieces();
const b64 = (grid) => {
  const buf = Buffer.alloc(32 * 32);
  for (let r = 0; r < 32; r++) for (let c = 0; c < 32; c++) buf[r * 32 + c] = grid[r][c];
  return buf.toString('base64');
};

/** One to three sentences per trait, from lore/traits.md. Keyed by display name. */
function loreByName() {
  const out = {};
  if (!fs.existsSync(LORE)) return out;
  const text = fs.readFileSync(LORE, 'utf8');
  // Entries look like: **Nocturne** — A flat night field ... (up to the blank line)
  const re = /^\*\*([^*]+)\*\*\s+[—-]\s+([\s\S]*?)(?=\n\n|\n\*\*|$)/gm;
  for (const m of text.matchAll(re)) {
    const name = m[1].trim();
    const body = m[2].replace(/\s+/g, ' ').trim();
    if (name && body && !out[name]) out[name] = body;
  }
  return out;
}
const lore = loreByName();

const pieces = {};
const categories = L.categories.map((key, id) => ({
  id,
  key,
  display: key[0].toUpperCase() + key.slice(1),
  traits: Array.from({ length: L.counts[key] }, (_, i) => {
    const p = L.byKey.get(`${key}/${i}`);
    pieces[`${key}/${i}`] = b64(p.grid);
    return { index: i, key: p.name, display: p.display, lore: lore[p.display] || '' };
  }),
}));

const data = {
  note: 'Generated by dapp/scripts/build-art.mjs from ../art. Do not edit.',
  canvas: { width: 32, height: 32 },
  layerOrder: L.layerOrder,
  palette: L.palette.colors.map((c) => c.hex),
  base: b64(L.byKey.get('base/0').grid),
  categories,
  pieces,
};

fs.writeFileSync(OUT, JSON.stringify(data));
const withLore = categories.flatMap((c) => c.traits).filter((t) => t.lore).length;
console.log(
  `pieces.json: ${Object.keys(pieces).length} traits + base, ${data.palette.length} colours, ` +
  `${withLore}/70 with lore — ${(fs.statSync(OUT).size / 1024).toFixed(0)} KB`,
);
